version: '3'

services:
  auth:
    build: ./auth
    ports:
      - "80:5000"

  business-logic:
    build: ./business_logic
    ports:
      - "81:5001"
    depends_on:
      - auth

  database:
    build: ./db
    ports:
      - "3306:3306"