apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: auth-app
        image: alex22docker/auth:latest
        ports:
        - containerPort: 5000
        env:
          - name: DB_HOST
            value: "db-app"
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: "Alex"
          - name: DB_PASSWORD
            value: "CloudComp10!"
          - name: BUSINESS_PORT
            value: "5001"
        imagePullSecrets:
        - name: auth-secret


