apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-logic-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: business-logic-app
  template:
    metadata:
      labels:
        app: business-logic-app
    spec:
      containers:
      - name: business-logic-app
        image: alex22docker/business_logic:latest
        ports:
        - containerPort: 5001
        env:
          - name: DB_HOST
            value: "db-app"
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: "Alex"
          - name: DB_PASSWORD
            value: "CloudComp10!"
        imagePullSecrets:
        - name: auth-secret

