apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-logic-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: business-logic-app
  template:
    metadata:
      labels:
        app: business-logic-app
    spec:
      containers:
      - name: business-logic-app
        image: alex22docker/business_logic:latest
        ports:
        - containerPort: 5001
      imagePullSecrets:
      - name: auth-secret

