apiVersion: v1
kind: Service
metadata:
  name: business-logic-service
spec:
  type: ClusterIP
  selector:
    app: business-logic-app
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001


