apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-app
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
      - name: db-app
        image: alex22docker/db:latest
        ports:
        - containerPort: 3306
      imagePullSecrets:
      - name: auth-secret
