apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
      - name: portainer
        image: portainer/portainer-ce:latest # Sau "my-custom-portainer" dacă ai construit o imagine personalizată
        ports:
        - containerPort: 30090
        volumeMounts:
        - mountPath: /data
          name: portainer-data
      imagePullSecrets:
      - name: auth-secret
      volumes:
      - name: portainer-data
        emptyDir: {}


